import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import HeaderIndex from "@/components/index/headerFooter/HeaderIndex";
import FooterIndex from "@/components/index/headerFooter/FooterIndex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Angelitos del Carmelo",
  description: "Generated by Joaquin Torres",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderIndex />
      <main>{children}</main>
      <FooterIndex />
    </>
  );
}
