import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import SideBarAdmin from "@/components/admin/sideBar/SideBarAdmin";
import ProtectedRoute from "@/components/provider/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Angelitos del Carmelo",
  description: "Generated by Joaquin Torres",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute rolesPermitidos={["admin"]}>
      <div className="flex">
        <SideBarAdmin />
        <main className="ml-64 p-6 w-full">{children}</main>
      </div>
    </ProtectedRoute>
  );
}
